CREATE TABLE PUBLIC.BOOKING (
    ORDER_NUMBER SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    ROOM_ID INTEGER,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
            REFERENCES PUBLIC.USER(ID),
    CONSTRAINT FK_ROOM
        FOREIGN KEY (ROOM_ID)
            REFERENCES PUBLIC.ROOM(ID)
);

drop table booking;