CREATE TABLE PUBLIC.USER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    EMAIL VARCHAR(320) NOT NULL UNIQUE,
    PHONE INTEGER NOT NULL UNIQUE
);

drop table public.user cascade ;